config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :tweets
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    mount_uploader :image, ImageUploader
    
    belongs_to :user
    validates :title,:material,:cost,:image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  validates :email,:nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :move_to_index, except: [:index, :show]

    def index
        @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
    end

    def new
        @tweets = Tweet.new
    end

    def show
        @tweet = Tweet.find(params[:id])    
    end

    def create
        Tweet.create(image: tweet_params[:image], text: tweet_params[:text], cost: tweet_params[:cost], title: tweet_params[:title], material: tweet_params[:material], cooking_type: tweet_params[:cooking_type], user_id: current_user.id)
        redirect_to root_path    #←これは記事一覧ページに飛ばすようにする！！！！！！！！！
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy if tweet.user_id == current_user.id
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        tweet = Tweet.find(params[:id])
        tweet.update(tweet_params) if tweet.user_id == current_user.id
    end
    
    private

    def tweet_params
        params.require(:tweet).permit(:text, :image, :cost, :title, :material, :cooking_type)
    end

    def move_to_index
        redirect_to action: :index unless user_signed_in?
    end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        user = User.find(params[:id])
        @nickname = user.nickname
        @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
        <h2 class="header__title">mini-pad</h2>
      <% if user_signed_in? %>
        <p class="header__name">こんにちは、<strong><%= current_user.nickname %></strong>さん</p>  
          <ul class="header__info uk-breadcrumb uk-text-bold">
            <li>
              <%= link_to "レシピを作る", new_tweet_path%>
            </li>
            <li>
              <%= link_to "マイページ", user_path(current_user.id)%>
            </li>
            <li>
              <%= link_to "サインアウト", destroy_user_session_path, method: :delete%>
            </li>
            <li>
              <%= link_to "ホームへ", root_path%>
            </li>
          </ul>  
        <% else %>
          <ul class="header__info uk-breadcrumb">
            <li>
              <%= link_to "サインイン", new_user_session_path%>
            </li>
            <li>
              <%= link_to "新規アカウント登録", new_user_registration_path%>
            </li>
            <li>
              <%= link_to "ホームへ", root_path%>
            </li>
          </ul>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tweets/_article.html.erb
<%# 記事がはいるところ %>
<div class="article">
    <div class="uk-card uk-card-default uk-grid-collapse uk-child-width-1-3@s uk-margin" uk-grid>
        <div class="uk-card-media-left uk-cover-container">
            <img src="<%= tweet.image %>" alt="" uk-cover>
            <canvas width="600" height="400"></canvas>
        </div>
        <div class="uk-card-body" style="position:relative">
            <h3 class="uk-card-title uk-heading-divider"><%= tweet.title %></h3>
            <mark><%= tweet.cooking_type %></mark>
            <div class="more">
                <ul class="more__list">
                    <li>
                        <%= link_to 'レシピ詳細', tweet_path(tweet.id), class: "uk-button uk-button-default" %>
                    </li>
                    <% if user_signed_in? && current_user.id == tweet.user_id %>
                    <li>
                        <%= link_to 'レシピ編集', edit_tweet_path(tweet.id), class: "uk-button uk-button-default"%>
                    </li>    
                    <li>
                        <%= link_to '削除', tweet_path(tweet.id), method: :delete, class: "uk-button uk-button-default"%>
                    </li>
                </ul>
                    <% end %>
            </div>
            <a href="/users/<%= tweet.user_id %>" class="more__user">
                <span>投稿者 : </span><%= tweet.user.nickname %>
            </a>
        </div>
    </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents-row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="uk-button uk-button-primary uk-button-large" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
<div class="form-style">
    <%= form_for @tweet do |f| %>
        <fieldset>
            <legend><span class="number">1</span> 料理を編集する</legend>
            <%= f.text_field :title, placeholder: "料理名 *" %>
            <%= f.text_area :material, placeholder: "材料 *" %>
            <%= f.text_field :cost, placeholder: "コスト *" %>
            <%= f.file_field :image %>
            <%= f.label :job , "料理種別:" %>
            <%= f.select :cooking_type, ["すし・魚料理", "和食・日本料理", "麺類", "丼もの・揚げ物", "粉物", "郷土料理", "アジア・エスニック", "中華", "イタリアン", "養殖・西洋料理", "フレンチ", "焼肉・ステーキ", "焼き鳥・串料理", "鍋", "スイーツ", "その他"], id: "job" %>
        </fieldset>
        <fieldset>
            <legend><span class="number">2</span> 説明を編集する</legend>
            <%= f.text_area :text, placeholder: "調理工程、料理の説明など" %>
        </fieldset>
        <%= f.submit %>
    <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents">
    <% @tweets.each do |tweet| %>
    <%= render partial: "article", locals: { tweet: tweet }%>
    <% end %>
</div>
<%= paginate(@tweets) %>

app/views/tweets/new.html.erb
<div class="form-style">
    <%= form_for @tweets do |f| %>
        <fieldset>
            <legend><span class="number">1</span> レシピを登録する</legend>
            <%= f.text_field :title, placeholder: "料理名 *" %>
            <%= f.text_area :material, placeholder: "材料 *" %>
            <%= f.text_field :cost, placeholder: "コスト *" %>
            <%= f.file_field :image %>
            <%= f.label :job , "料理種別:" %>
            <%= f.select :cooking_type, ["すし・魚料理", "和食・日本料理", "麺類", "丼もの・揚げ物", "粉物", "郷土料理", "アジア・エスニック", "中華", "イタリアン", "養殖・西洋料理", "フレンチ", "焼肉・ステーキ", "焼き鳥・串料理", "鍋", "スイーツ", "その他"], id: "job" %>
        </fieldset>
        <fieldset>
            <legend><span class="number">2</span> 説明をつける</legend>
            <%= f.text_area :text, placeholder: "調理工程、料理の説明など" %>
        </fieldset>
        <%= f.submit %>
    <% end %>
</div>

app/views/tweets/show.html.erb
<div class="uk-container">
    <div class="uk-container__header">
        <h2 class="uk-container__header__title uk-heading-divider"><%= @tweet.title%>  <ins>(<%= @tweet.cooking_type%>)</ins></h2>
    </div>
    <div class="uk-container__comment">
        <%= @tweet.text%>
        <a href="/users/<%= @tweet.user_id %>" class="uk-container__comment__user">
            <span>投稿者 : </span><%= @tweet.user.nickname %>
        </a>
    </div>
    <div class="uk-container__image">
        <img src="<%= @tweet.image%>" alt="">
    </div>
    <div class="uk-container__cost">
        <h3 class="uk-heading-divider">コスト</h3>
        <%= @tweet.cost%>
    </div>
    <div class="uk-container__material">
        <h3 class="uk-heading-divider">材料</h3>
        <%= simple_format(@tweet.material)%>
    </div>
</div>

app/views/tweets/update.html.erb
<div class="contents-row">
    <div class="success">
      <h3>
        <strong>更新が完了しました。</strong>
      </h3>
      <a class="uk-button uk-button-primary uk-button-large" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/_article.html.erb
<%# 記事がはいるところ %>
<div class="article">
    <div class="uk-card uk-card-default uk-grid-collapse uk-child-width-1-3@s uk-margin" uk-grid>
        <div class="uk-card-media-left uk-cover-container">
            <img src="<%= tweet.image %>" alt="" uk-cover>
            <canvas width="600" height="400"></canvas>
        </div>
        <div class="uk-card-body" style="position:relative">
            <h3 class="uk-card-title uk-heading-divider"><%= tweet.title %></h3>
            <mark><%= tweet.cooking_type %></mark>
            <div class="more">
                <ul class="more__list">
                    <li>
                        <%= link_to 'レシピ詳細', tweet_path(tweet.id), class: "uk-button uk-button-default" %>
                    </li>
                    <% if user_signed_in? && current_user.id == tweet.user_id %>
                    <li>
                        <%= link_to 'レシピ編集', edit_tweet_path(tweet.id), class: "uk-button uk-button-default"%>
                    </li>    
                    <li>
                        <%= link_to '削除', tweet_path(tweet.id), method: :delete, class: "uk-button uk-button-default"%>
                    </li>
                </ul>
                    <% end %>
            </div>
            <a href="/users/<%= tweet.user_id %>" class="more__user">
                <span>投稿者 : </span><%= tweet.user.nickname %>
            </a>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<h3 class="uk-text-center"><%= @nickname %>さんの投稿一覧</h3>
    <% @tweets.each do |tweet| %>
    <%= render partial: "article", locals: { tweet: tweet}%>
    <% end %>
    <%= paginate(@tweets) %>
</div>